[2017-01-13 00:51:21,823][app.LiveChecker][ERROR] 无法连接https://www.douyu.com/column_rank_list/getRoomLiveStatusAndCategoryByRoomID?room_id=joker
Traceback (most recent call last):
  File "/home/jack/pythoncoding/easySee/app/LiveChecker.py", line 31, in douyu
    is_live = response.get("data").get(anchor.room).get("is_live")
AttributeError: 'list' object has no attribute 'get'
[2017-01-13 00:58:57,155][app.LiveChecker][ERROR] 无法连接https://www.douyu.com/column_rank_list/getRoomLiveStatusAndCategoryByRoomID?room_id=dushuren
Traceback (most recent call last):
  File "/home/jack/pythoncoding/easySee/app/LiveChecker.py", line 31, in douyu
    is_live = response.get("data").get(anchor.room).get("is_live")
AttributeError: 'list' object has no attribute 'get'
[2017-01-13 14:39:23,435][app.LiveChecker][ERROR] 无法连接http://www.panda.tv/10091
Traceback (most recent call last):
  File "/home/jack/pythoncoding/easySee/app/LiveChecker.py", line 39, in xiongmao
    r = self.s.get(url, proxies=random.choice(PROXIES)).text
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/jack/easyenv/local/lib/python2.7/site-packages/requests/adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
